# Generated by Django 6.1 on 2026-09-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadVoluntario',
            fields=[
                ('id_actividad_asignada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'actividad_voluntario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('entidad_tipo', models.CharField(max_length=50)),
                ('entidad_id', models.IntegerField()),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_generada', models.DateTimeField()),
                ('atendida', models.BooleanField()),
            ],
            options={
                'db_table': 'alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalResponsable',
            fields=[
                ('id_animal_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_responsabilidad', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaDiagnosticoPatologia',
            fields=[
                ('id_consulta_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consulta_diagnostico_patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('anamesis', models.TextField(blank=True, null=True)),
                ('hallazgos_examen', models.TextField(blank=True, null=True)),
                ('resultado_estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrada', models.DateTimeField()),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'entradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosAnimal',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'estados_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosPeticion',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'estados_peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciasPeticion',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_subida', models.DateTimeField()),
            ],
            options={
                'db_table': 'evidencias_peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormatoSeresSintientes',
            fields=[
                ('id_formato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField()),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('diagnostico_breve', models.TextField(blank=True, null=True)),
                ('acciones_realizadas', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'formato_seres_sintientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('estado_general', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'historia_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoAnimal',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_estado_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('principio_activo', models.CharField(blank=True, max_length=150, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('concentracion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cie', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'patologias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('ciudadano_id', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peticiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedencias',
            fields=[
                ('id_procedencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'procedencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedimientosCatalogo',
            fields=[
                ('id_procedimiento_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'procedimientos_catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedimientosRealizados',
            fields=[
                ('id_procedimiento_realizado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_anexo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'procedimientos_realizados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'responsables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('tipo_salida', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'salidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPeticiones',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('accion_realizada', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seguimiento_peticiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientosClinicos',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('evolucion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seguimientos_clinicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposActividad',
            fields=[
                ('id_tipo_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposPeticion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tipos_peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientosAplicados',
            fields=[
                ('id_tratamiento_aplicado', models.AutoField(primary_key=True, serialize=False)),
                ('dosis_frecuencia_duracion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tratamientos_aplicados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientosCatalogo',
            fields=[
                ('id_tratamiento_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tratamientos_catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinarios',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tarjeta_profesional', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'veterinarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_postulacion', models.DateField()),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'voluntarios',
                'managed': False,
            },
        ),
    ]
