# Generated by Django 6.1 on 2026-09-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
