# Generated by Django 6.1 on 2026-09-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260906_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcedimientosCatalogo',
        ),
        migrations.DeleteModel(
            name='ProcedimientosRealizados',
        ),
    ]
