# Generated by Django 6.1.1 on 2026-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_procedimientoscatalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionMedicamento',
            fields=[
                ('id_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('dosis_administrada', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administracion_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('anamnesis', models.TextField(blank=True, null=True)),
                ('hallazgos_examen', models.TextField(blank=True, null=True)),
                ('resultado_estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id_detalle_salida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPatologia',
            fields=[
                ('id_diagnostico_patologia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'diagnostico_patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'especies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPeticiones',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estado_peticiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaPeticiones',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'evidencia_peticiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'examen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalizacionSeresSintientes',
            fields=[
                ('id_hospitalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospitalizacion_seres_sintientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_cie', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoRealizado',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procedimiento_realizado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoHospitalario',
            fields=[
                ('id_seguimiento_hosp', models.AutoField(primary_key=True, serialize=False)),
                ('evolucion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seguimiento_hospitalario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPeticionesVisita',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seguimiento_peticiones_visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPeticion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposEventos',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientoMedicamentos',
            fields=[
                ('id_tratamiento_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tratamiento_medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitaAnimal',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visita_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoluntarioEvento',
            fields=[
                ('id_voluntario_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voluntario_evento',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ActividadVoluntario',
        ),
        migrations.DeleteModel(
            name='Alertas',
        ),
        migrations.DeleteModel(
            name='ConsultaDiagnosticoPatologia',
        ),
        migrations.DeleteModel(
            name='Consultas',
        ),
        migrations.DeleteModel(
            name='Entradas',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='EstadosPeticion',
        ),
        migrations.DeleteModel(
            name='EvidenciasPeticion',
        ),
        migrations.DeleteModel(
            name='FormatoSeresSintientes',
        ),
        migrations.DeleteModel(
            name='HistorialEstadoAnimal',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Patologias',
        ),
        migrations.DeleteModel(
            name='Procedencias',
        ),
        migrations.DeleteModel(
            name='SeguimientoPeticiones',
        ),
        migrations.DeleteModel(
            name='TiposActividad',
        ),
        migrations.DeleteModel(
            name='TiposPeticion',
        ),
        migrations.DeleteModel(
            name='TratamientosAplicados',
        ),
        migrations.DeleteModel(
            name='TratamientosCatalogo',
        ),
        migrations.DeleteModel(
            name='Veterinarios',
        ),
        migrations.DeleteModel(
            name='Voluntarios',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
