# Generated by Django 6.1.1 on 2026-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_administracionmedicamento_compra_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
