# Generated by Django 6.1.1 on 2026-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_salida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='principio_activo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamentos',
        ),
    ]
