# Generated by Django 6.1 on 2026-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientosCatalogo',
            fields=[
                ('id_procedimiento_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'procedimientos_catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedimientosRealizados',
            fields=[
                ('id_procedimiento_realizado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_anexo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'procedimientos_realizados',
                'managed': False,
            },
        ),
    ]
