# Generated by Django 6.1 on 2026-09-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_clinicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimientoscatalogo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='procedimientosrealizados',
            options={'managed': True},
        ),
    ]
