# Generated by Django 6.1.1 on 2026-09-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_clinicos', '0002_alter_procedimientoscatalogo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimientoscatalogo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='procedimientosrealizados',
            options={'managed': False},
        ),
    ]
