# Generated by Django 6.1.1 on 2026-09-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_clinicos', '0003_alter_procedimientoscatalogo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcedimientosCatalogo',
        ),
        migrations.DeleteModel(
            name='ProcedimientosRealizados',
        ),
    ]
