# Generated by Django 6.1.1 on 2026-09-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='especie',
            table='especies',
        ),
    ]
