# Generated by Django 6.1 on 2026-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_solicitudadopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionanimal',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
