# Generated by Django 6.1 on 2026-09-26 06:29

from django.db import migrations


def limpiar_imagenes_antiguas(apps, schema_editor):
    """Los registros viejos guardaban rutas locales (ej: 'adopciones/rocky.jpg')
    que apuntaban a archivos del servidor que ya no existen y devolvían 404.
    Se dejan sin imagen para que los clientes muestren su imagen por defecto."""
    AdopcionAnimal = apps.get_model('adopciones', 'AdopcionAnimal')
    (
        AdopcionAnimal.objects
        .exclude(imagen__isnull=True)
        .exclude(imagen='')
        .update(imagen=None)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_alter_adopcionanimal_imagen'),
    ]

    operations = [
        migrations.RunPython(limpiar_imagenes_antiguas, migrations.RunPython.noop),
    ]
