# Generated by Django 6.1 on 2026-10-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0004_limpiar_imagenes_antiguas'),
        ('animales', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adopcion', to='animales.animal'),
        ),
    ]
