# Generated by Django 6.1 on 2026-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_alter_solicitudadopcion_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdopcionAnimal',
        ),
    ]
