# Generated by Django 6.1 on 2026-09-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patología',
                'verbose_name_plural': 'Patologías',
                'db_table': 'patologia',
            },
        ),
    ]
