# Generated by Django 6.1.1 on 2026-09-10 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='voluntariado_eventos/')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('identificacion', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluntariado.eventovoluntariado')),
            ],
        ),
    ]
