# Generated by Django 6.1 on 2026-09-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usuarios_telefono'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposEventos',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoluntarioEvento',
            fields=[
                ('id_voluntario_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voluntario_evento',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='postulacionvoluntariado',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='postulacionvoluntariado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_voluntariado', to='users.usuarios'),
        ),
        migrations.AlterField(
            model_name='postulacionvoluntariado',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postulacionvoluntariado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='voluntariado.eventovoluntariado'),
        ),
        migrations.AlterField(
            model_name='postulacionvoluntariado',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='postulacionvoluntariado',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='eventovoluntariado',
            table='voluntariado_eventovoluntariado',
        ),
        migrations.AlterModelTable(
            name='postulacionvoluntariado',
            table='voluntariado_postulacionvoluntariado',
        ),
    ]
